{% set name = "flet-core" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flet_core-{{ version }}.tar.gz
  sha256: e46f2ab77b8efbbc3a971cac4ddcf2358a9e8d7b9e0997bbfb92993d7bb5777a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core
    - python >=3.7,<4.0
  run:
    - python >=3.7,<4.0
    - typing-extensions >=4.4.0,<5.0.0
    - repath >=0.9.0,<1.0.0

test:
  imports:
    - flet_core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/flet-dev/flet
  dev_url: https://github.com/flet-dev/flet/tree/main/sdk/python/packages/flet-core
  summary: Flet core library for Flet framwork sdk development.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
